TOC and file renaming
TriliumNext/Docs pull request #88
Opened 2024-07-06 17:42 UTC by root-hal9000

- renamed all files to be lowercase and have no spaces
- Updated all references to those names in file content
- Recreated table of contents into readme.MD Issue #2
- Separated "importing docs" text into a separate file
- Added a few %%{WARNING}%% tags to links that go to zadams repos. Issue #87

2024-07-06 17:52 UTC, Alumniminium commented
seems to have overwritten my changes to the web-clipper.md, could you pull that into your merge request please :)

2024-07-06 17:53 UTC, Alumniminium commented on Wiki/web-clipper.md
Please copy the contents from https://github.com/TriliumNext/Docs/blob/main/Wiki/Web-clipper.md

2024-07-06 19:35 UTC, Alumniminium requested changes
Please delete the old files with MixedCase.

2024-07-06 23:04 UTC, root-hal9000 commented
> Please delete the old files with MixedCase.

Oops, sorry about that, they had been deleted (I originally renamed them with a bash script) but I had issues commiting and re-cloned to copy my changes over and didn't notice that. Will do

2024-07-06 23:29 UTC, root-hal9000 commented
OK, deleted the old files - anything else here or should I merge. If someone merges, create a new initial-review branch from main after merging this

2024-07-07 14:39 UTC, maphew commented
was all of this work scripted? I presume yes or mostly. Perhaps put them in `/utils` or something, or at least keep the transition scripts handy in the event there's more changes upstream. I don't think there's a high probability of that, but have been bitten many times in the past by the thought "we'll only need to do this once" ... ;-)

2024-07-07 14:45 UTC, root-hal9000 commented
> was all of this work scripted? I presume yes or mostly.
Only the renaming of the files to lowercase/no space (and replacing of the links referring to them). The TOC was manual as there's no inherent structure in the files for that and I made some slight changes to the order

2024-07-07 18:56 UTC, Alumniminium approved these changes

2024-07-07 18:57 UTC, merged

2024-07-07 19:01 UTC, Alumniminium commented
oh god i should have merged that from the terminal and not from the web... what just happened

2024-07-07 19:15 UTC, root-hal9000 commented
> oh god i should have merged that from the terminal and not from the web... what just happened

Just got out of the meeting, not sure what you're referring too although I see a couple of new branches?

Also, I should have made the PR to the main branch, no? We should merge this into main, and then pull the initial-review branch from there

2024-07-08 06:18 UTC, Alumniminium commented
> [...] Also, I should have made the PR to the main branch, no? We should merge this into main, and then pull the initial-review branch from there

Feel free to do that, otherwise I'll do that tonight after work.

2024-07-08 17:26 UTC, Alumniminium commented
Done. I've merged that branch into main and created an 'initial-review' branch from the new main. @root-hal9000